### ISSUE TITLE
Error with null safety

### ISSUE THREAD

**Issue by robcleghorn** [jifalops/geomag#2]
This has been very useful package for me, however I get the following error when I try to calculate declination, seems related to upgrading to null safety.

E/flutter (12202): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: type 'Null' is not a subtype of type 'double'
E/flutter (12202): #0      GeoMag._geoMagFactory.<anonymous closure> (package:geomag/src/geomag.dart:403:53)
E/flutter (12202): #1      GeoMag.calculate (package:geomag/src/geomag.dart:35:25)

Any help is appreciated.

**Comment by robcleghorn** [comment]
BTW I get the issue running your test suite

package:geomag/src/geomag.dart 403:53  GeoMag._geoMagFactory.<fn>
package:geomag/src/geomag.dart 35:25   GeoMag.calculate
test/geomag_test.dart 36:25            runTest.<fn>.<fn>

type 'Null' is not a subtype of type 'double'

**Comment by robcleghorn** [comment]
This tweak seems to fix the issue, not sure if defaulting to 0 when GV is null is correct though.

`return GeoMagResult._(dec, dip, ti, bh, bx, by, bz, glat, glon, gv ?? 0, epoch);`

**Comment by shlima** [comment]
same here

**Comment by robcleghorn** [comment]
looks good, PR?

**Comment by shlima** [comment]
Not sure that it is the correct way to fix the issue

**Comment by shlima** [comment]
@jifalops do you have any plans to fix this issue ?

**Comment by robcleghorn** [comment]
nudge.

**Comment by jifalops** [comment]
Sorry everyone! This was just fixed in version 0.2.1.
